# name: Cypress training CI

# on:
#   push
#   # schedule:
#   # - crone: '0 4 * * 1-5'

# jobs:
#   install:
#     runs-on: ubuntu-latest

#     steps:
#       # uruchamia sie wewnatrz joba
#       - uses: actions/checkout@v4 # check the latest version
#       - name: Use Node.js 18
#         uses: actions/setup-node@v4 # check the latest version
#         with:
#         node-version: 18
#         # stawi srodowisko, jak apka gdzies stoi, to wywalamy:
#       - name: Checkout external repository
#         uses: actions/checkout@v4
#         with:
#         repository: "slawekradzyminski/awesome-localstack"
#         path: "awesome-localstack"
#       - name: Run Docker Compose
#         run: |
#           cd awesome-localstack
#           chmod +x run-docker-compose-ci.sh
#           ./run-docker-compose-ci.sh
#         ###
#       - run: npm install
#       - uses: browser-actions/setup-chrome@v1
#       - name: Run Cypress tests
#         run: npx cypress run --browser chrome
name: Cypress training CI

on: push

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Checkout external repository
        uses: actions/checkout@v4
        with:
          repository: "slawekradzyminski/awesome-localstack"
          path: "awesome-localstack"
      - name: Run Docker Compose
        run: |
          cd awesome-localstack
          chmod +x run-docker-compose-ci.sh
          ./run-docker-compose-ci.sh
      - run: npm install
      - uses: browser-actions/setup-chrome@v1
      - name: Run Cypress tests
        run: npx cypress run --browser chrome

  firefox-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Checkout external repository
        uses: actions/checkout@v4
        with:
          repository: "slawekradzyminski/awesome-localstack"
          path: "awesome-localstack"
      - name: Run Docker Compose
        run: |
          cd awesome-localstack
          chmod +x run-docker-compose-ci.sh
          ./run-docker-compose-ci.sh
      - run: npm install
      - uses: browser-actions/setup-firefox@v1
      - name: Run Cypress tests
        run: npx cypress run --browser firefox        
